const GH_TOKEN = process.env.GH_TOKEN;
const REPO = process.env.REPO;
const STALE_DAYS = Number(process.env.STALE_DAYS || 9);
const LABEL = 'workflow-health';

if (!GH_TOKEN) { console.error('Missing GH_TOKEN'); process.exit(1); }
if (!REPO) { console.error('Missing REPO'); process.exit(1); }

const API = `https://api.github.com/repos/${REPO}`;
const HEADERS = {
  Authorization: `Bearer ${GH_TOKEN}`,
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
};

async function gh(path, options = {}) {
  const res = await fetch(`${API}${path}`, {
    ...options,
    headers: { ...HEADERS, ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers },
  });
  return res;
}

async function listWorkflows() {
  const res = await gh('/actions/workflows?per_page=100');
  if (!res.ok) throw new Error(`List workflows failed: ${res.status} ${await res.text()}`);
  const data = await res.json();
  // Only guard workflows defined in this repo; skips GitHub-managed dynamic
  // workflows like pages-build-deployment, which cannot be enabled via this API.
  return data.workflows.filter(w => w.path.startsWith('.github/workflows/'));
}

async function lastScheduledRun(workflowId) {
  const res = await gh(`/actions/workflows/${workflowId}/runs?event=schedule&per_page=1`);
  if (!res.ok) return null;
  const data = await res.json();
  return data.workflow_runs?.[0] ?? null;
}

async function enableWorkflow(workflowId) {
  const res = await gh(`/actions/workflows/${workflowId}/enable`, { method: 'PUT' });
  return res.ok;
}

async function getOpenIssues() {
  const res = await gh(`/issues?labels=${LABEL}&state=open`);
  if (!res.ok) return [];
  const issues = await res.json();
  return Array.isArray(issues) ? issues : [];
}

async function ensureLabel() {
  const res = await gh('/labels', {
    method: 'POST',
    body: JSON.stringify({ name: LABEL, color: 'd93f0b', description: 'Automated workflow health guard findings' }),
  });
  // 422 = already exists — fine.
  if (!res.ok && res.status !== 422) console.warn(`Label create returned ${res.status}`);
}

async function report(findings) {
  const today = new Date().toISOString().slice(0, 10);
  const body = `## Workflow Health Guard — ${today}\n\n${findings.map(f => `- ${f}`).join('\n')}\n\n---\n*Generated by the [Workflow Health Guard](../../actions/workflows/workflow-health.yml). Auto-re-enabled workflows need no action; manually disabled or stale ones need a human decision.*`;
  const open = await getOpenIssues();
  if (open.length > 0) {
    const res = await gh(`/issues/${open[0].number}/comments`, { method: 'POST', body: JSON.stringify({ body }) });
    if (!res.ok) throw new Error(`Comment failed: ${res.status} ${await res.text()}`);
    console.log(`Appended findings to existing issue #${open[0].number}`);
    return;
  }
  await ensureLabel();
  const res = await gh('/issues', {
    method: 'POST',
    body: JSON.stringify({ title: `Workflow Health Guard: attention needed [${today}]`, body, labels: [LABEL] }),
  });
  if (!res.ok) throw new Error(`Issue create failed: ${res.status} ${await res.text()}`);
  console.log(`Issue created: ${(await res.json()).html_url}`);
}

async function closeOpenIssues() {
  for (const issue of await getOpenIssues()) {
    await gh(`/issues/${issue.number}`, {
      method: 'PATCH',
      body: JSON.stringify({ state: 'closed', state_reason: 'completed' }),
    });
    console.log(`All workflows healthy — closed issue #${issue.number}`);
  }
}

async function main() {
  const workflows = await listWorkflows();
  console.log(`Checking ${workflows.length} workflows in ${REPO}...`);
  const findings = [];
  const now = Date.now();

  for (const w of workflows) {
    const last = await lastScheduledRun(w.id);
    const hasSchedule = last !== null;

    if (w.state === 'disabled_inactivity') {
      const ok = await enableWorkflow(w.id);
      findings.push(ok
        ? `**Auto-remediated:** \`${w.name}\` was disabled by GitHub's 60-day inactivity policy — re-enabled automatically.`
        : `**FAILED to re-enable** \`${w.name}\` (disabled_inactivity) — re-enable manually: \`gh workflow enable "${w.name}" --repo ${REPO}\``);
      console.log(`${w.name}: disabled_inactivity -> re-enable ${ok ? 'OK' : 'FAILED'}`);
      continue;
    }
    if (w.state === 'disabled_manually') {
      findings.push(`**Manually disabled:** \`${w.name}\` — intentional? Re-enable it or delete \`${w.path}\`. Not auto-re-enabled (respecting human intent).`);
      console.log(`${w.name}: disabled_manually — flagged, not touched`);
      continue;
    }
    if (w.state !== 'active') {
      findings.push(`**Unexpected state \`${w.state}\`:** \`${w.name}\` — investigate.`);
      console.log(`${w.name}: unexpected state ${w.state}`);
      continue;
    }

    if (hasSchedule) {
      const ageDays = (now - Date.parse(last.created_at)) / 86400000;
      if (ageDays > STALE_DAYS) {
        findings.push(`**Stale schedule:** \`${w.name}\` is active but its last scheduled run was ${Math.floor(ageDays)} days ago (threshold ${STALE_DAYS}). Check the workflow's run history and cron.`);
        console.log(`${w.name}: stale — last scheduled run ${Math.floor(ageDays)}d ago`);
      } else {
        console.log(`${w.name}: healthy (last scheduled run ${ageDays.toFixed(1)}d ago)`);
      }
      // Keepalive ping: enabling an already-active workflow is a no-op for its
      // state but resets GitHub's 60-day scheduled-workflow inactivity clock,
      // so crons keep firing even through commit-quiet stretches.
      await enableWorkflow(w.id);
    } else {
      console.log(`${w.name}: active (no scheduled runs — event-driven only)`);
    }
  }

  if (findings.length === 0) {
    await closeOpenIssues();
    console.log('All workflows healthy.');
    return;
  }
  await report(findings);
  const needsHuman = findings.some(f => !f.startsWith('**Auto-remediated:**'));
  if (needsHuman) process.exit(1);
}

main().catch(err => { console.error(err); process.exit(1); });
